In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)
# version 1.10.0+cu111 for video

2.1.0+cu118


## **Intro to Tensors**

In [ ]:
# scalar via torch.tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# single number
scalar.ndim

0

In [ ]:
# scalar back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7 , 7])

print(vector.ndim) # 1
print(vector.shape) # torch.Size([2]) 2 by 1 elements = 2 elements

1
torch.Size([2])


In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                        [9,10]])
MATRIX
# tensor([[ 7,  8],
#        [ 9, 10]])

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim # 2

2

In [ ]:
MATRIX[0] # tensor([7, 8]), MATRIX[1] = tensor([9,10])

tensor([7, 8])

In [ ]:
print(MATRIX.ndim) # 1
print(MATRIX.shape) # torch.Size([2, 2]) = 4 elements

2
torch.Size([2, 2])


In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(TENSOR.ndim) # 3
print(TENSOR.shape) # torch.Size([1, 3, 3]) : 0th dim = 1, 1st dim = 3, 2nd dim = 3 : Outer most bracket is dim0 {1 dimensional object}, next is dim1 {3 arrays}, next is dim2 {3 elements}, next is dimN in every index.

3
torch.Size([1, 3, 3])


 # Scalars and Vectors are lower case. MATRIX AND TENSORS ARE IN UPPER CASE.



# **Random Tensors**

Why random tensors?

Random tensors are needed because the way that many NN learn is that they start with random datasets and slowly adjust to those number to better represent the data.

`Start Random -> Look -> Update -> Look -> Update`

In [ ]:
# create random tensor of size(3, 4) ALWAYS A FLOAT32
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.6565, 0.0514, 0.3905],
         [0.6181, 0.1280, 0.6014],
         [0.0711, 0.8982, 0.9504],
         [0.0908, 0.2545, 0.3690]],

        [[0.1871, 0.9655, 0.2788],
         [0.8014, 0.3205, 0.1571],
         [0.8271, 0.0974, 0.1052],
         [0.2428, 0.0580, 0.4600]],

        [[0.8127, 0.1120, 0.8880],
         [0.8582, 0.7308, 0.8678],
         [0.9040, 0.6165, 0.6934],
         [0.7817, 0.7858, 0.0638]]])

In [ ]:
# Create a random tensor with a similar shape to an image tensor

# SPLIT BY COLOR CHANNELS TO MANIPULATE IMAGES

random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and Ones

In [ ]:
# Create a tensor of all zeros ( GOOD FOR MASKS AKA BOOLEANS )
# Typical case: use matrix multiplication to use mask ( zeros * randomtensor )

zeros =  torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


# Create a Range of Tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensors like, is like mimicking to produce a copy of a tensor with a similar shape

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Attributes

### Common Errors

1. Tensors are not in the right dtype - get datatype from tensor, use `tensor.dtype`
2. Tensors are not the right shape - get shape from tensor, use `tensor.shape`
3. Tensors are not on the right device - get which device from tensor, use `tensor.device` (CPU or GPU)

In [ ]:
# FLOAT32 TENSOR
f32_tensor = torch.rand((3, 4),
                          dtype=None, # What dtype is the tensor?
                          device=None, # What device is it on? "cuda" or etc
                          requires_grad=False # Whether or not to track gradients with this tensors operations
                          )

# Tensor Attributes
print(f"Show object: {f32_tensor}")
print(f"Shape of Tensor: {f32_tensor.shape}")
print(f"Datatype of Tensor: {f32_tensor.dtype}")
print(f"Device of Tensor: {f32_tensor.device}")


Show object: tensor([[0.6551, 0.3007, 0.9243, 0.3145],
        [0.1364, 0.9601, 0.6580, 0.1764],
        [0.3642, 0.2445, 0.7139, 0.3398]])
Shape of Tensor: torch.Size([3, 4])
Datatype of Tensor: torch.float32
Device of Tensor: cpu


# Manipulating Tensors (Tensor Operations)

1. Addition / Subtraction (element-wise)
2. Multiplication / Division (element-wise)
3. Matrix Multiplication

In [ ]:
# Add
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Pytorch In-Built Functions ( GENERALLY USE NORMAL OPERATORS )
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([10, 20, 30])

# Matrix Multiplication

Two main ways to multiply a matrix:
1. Dot Product
2. Element-wise or Scalar multiplication.

In [ ]:
# Element
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Dot Product or (1*1 + 2*2 + 3*3)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# For Loop vs Vectorized

%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.77 ms, sys: 0 ns, total: 1.77 ms
Wall time: 1.83 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 394 µs, sys: 764 µs, total: 1.16 ms
Wall time: 1.23 ms


tensor(14)